name: Go Build and Upload EXE on Push

on:
  push:
    branches:
      - master
  workflow_dispatch:  # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build Windows EXE
        run: |
          mkdir -p build
          GOOS=windows GOARCH=amd64 go build -o build/xyzw.exe ./cmd/xyzw

      - name: Create zip package
        run: |
          cd build
          zip xyzw_windows.zip xyzw.exe

      - name: Upload to "latest" Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: build/xyzw_windows.zip
          make_latest: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
