name: Go Build and Upload EXE on Push

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Get latest tag and bump version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          release_branches: master
          default_bump: patch  # 可改为 major 或 minor

      - name: Build Windows EXE
        run: |
          mkdir -p build
          GOOS=windows GOARCH=amd64 go build -o build/xyzw.exe ./cmd/xyzw

      - name: Create zip package
        run: |
          cd build
          zip xyzw_windows.zip xyzw.exe

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          files: build/xyzw_windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
